 
 /*------------------------------------------------------------------------
    File        : Colors
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : dlampe
    Created     : Wed Mar 16 13:12:54 CET 2016
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.


ENUM Colors.

DEFINE ENUM       Red
Blue
Green
Yellow
White
Black
Gray
Grey = Gray.
END.
